spring:
  application:
    name:
      WatchService
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/watch_service
    username: dorian
    password: dorian01

  flyway:
    locations: classpath:/db/migration
    schemas: public
    baseline-on-migrate: true
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none